### ISSUE TITLE
New Item: Chain Bomb

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#133]
### The Basics

This is rly similar to bomb, but is throwable, and if it hits an entity(block, player, turip) the entity will have a bomb go off inside of it. this can also chain, and could theoretically do big damage if you stack enough blocks on someone.

### Why add this?

replacement for bomb so we can still break blocks, and also itemmmmmmmmmmm

### Voting

👍 = Yes
👎 = No (comment why)

**Comment by 3foe** [comment]
so dynamite but different how about this

**The Basics**
it is a throwable chainsaw, it does tick damage to everything it hits so it is AOE it will slow down any tanks because it "slashed their tires" The DPS is TBD

**Why add it**
it takes out turret campers so you cant stack turrets, it slows tanks for a little bit so it counters flatting, it still has the block breaking buff but it also is not a viable damage item, it does not buff tactile because it does DPS, not instant damage, this is spike and bomb and airstrike combined 3 unused items with situational advantages since it has the advantages of all 3 it becomes viable

**Comment by LostKing73** [comment]
spam ew. . .

**Comment by BreadSpammer** [comment]
like it's too gud for blocks, and if u try to combo it with blocks, why? that's 3 slots just to die to a fire tank and lack of healing items.

**Comment by LostKing73** [comment]
block and this, then BOOM

**Comment by LostKing73** [comment]
Situational
