### ISSUE TITLE
New Item: Rage

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#134]
### The Basics 

Splashes a pink bottle of "rage" on the floor, creating a circle where you and your teammates gain +50% firerate and cooldown time. 

### Why add this? 

itemmmmmmmmmm also coooooool

### Voting

👍 = Yes
👎 = No (comment why)

**Comment by LostKing73** [comment]
ez quality spam lol

**Comment by 3foe** [comment]
upgrade time

**Comment by LostKing73** [comment]
what?

**Comment by 3foe** [comment]
**The Basics**

you use a bottle of coolant (commonly used in machines to cool it down) to increase you fire rate by 50% it does not effect you teammates after you use it you have a burn out, you fire rate is slightly decreased

**why add it**
it adds a new item that can help you catch flats because you have more shots so a higher chance to hit, it can help shotgun pvp

**Comment by 3foe** [comment]
better name and better uses :D without the team thing because rage doesn't make sense

**Comment by LostKing73** [comment]
like spam ew

**Comment by BreadSpammer** [comment]
eh.. clash royale rip-off, and just ruins ppl's shotgun timings. also not electronics and tanks themed

**Comment by LostKing73** [comment]
> eh.. clash royale rip-off, and just ruins ppl's shotgun timings. also not electronics and tanks themed

howd u know :D
