### ISSUE TITLE
Repost

### ISSUE THREAD

**Issue by cs6413110** [cs6413110/Pixel-Tanks#159]
@BreadSpammer @LostKing73 MENUS NOW

@BreadSpammer - Shop Menu #1 PRIORITY
- Image, description, price
- Lock image size should be consistent with perk/class tab sizes
- Re-add background
- FIX

@LostKing73 - Need multiplayer menu
- I need a text slot
- FFA, TDM, and Duels (scrapping defense) buttons
- Play button
- 3 buttons for saved servers
- 1 button for direct connect
- 3 buttons for saving an ip to one of the servers (Save/Set 1, Save/Set 2, etc.)
- I can give you a notebook drawing or soemthing at lunch

**Comment by LostKing73** [comment]
huh

**Comment by LostKing73** [comment]
so like, my issue is that i think yalls 1000x1000 style is ugly. so like can I do smth different or what

**Comment by cs6413110** [comment]
Ye just same aspect ratio

**Comment by cs6413110** [comment]
normally we upscale from 400x250 to 1600x1000

**Comment by cs6413110** [comment]
You could technically go as small as 40x25 idk

**Comment by LostKing73** [comment]
perfect 40x25 it is

**Comment by LostKing73** [comment]
lol, whats in between 400x250 and 40x25

**Comment by cs6413110** [comment]
just desmos it?
uhmm...
80x50
160x100

**Comment by LostKing73** [comment]
oh. my. goodness. @cs6413110 . please do smth abt flat. he deleted my lore for his cringe roblox lore

**Comment by cs6413110** [comment]
bro not roblox

**Comment by LostKing73** [comment]
pls halp

**Comment by cs6413110** [comment]
Just make menu and get me his "terms of admin abuse" from months ago on discord and I'll insta

**Comment by 3foe** [comment]
bru I didn't mess with your lore. IT IS STILL THERE. also admin abuse was never put into effect :)

**Comment by 3foe** [comment]
![image](https://github.com/user-attachments/assets/3f50ba3c-8bf6-459d-b1aa-4a47317ed6ec)
![image](https://github.com/user-attachments/assets/155093de-a422-4c0e-b42d-2fef46b6e4a1)

**Comment by 3foe** [comment]
I added a storyline so your leviathan can make sense

**Comment by LostKing73** [comment]
> I added a storyline so your leviathan can make sense

shut up. you don't get to have respect from me anymore. you should not have touched that.

**Comment by LostKing73** [comment]
@cs6413110 .

paste this in please.

Key Locations
The Surface - Now ravaged by The War, the surface is a barren, uninhabitable wasteland. In the past, there used to be great lakes and lush forests. These days, a battle or two may be hosted, but usually, everyone tends to stay away due to the radioactivity.

Battlegrounds - The normal competition area of the game. Frequently used for recreational battles in Free For All, however, dueling RED and BLUE teams may still appear to battle in a game of Team Death Match. Sometimes, the tanks must team up to defend against invading AIs.

Cave - A cave that is perfectly carved to host battles. Surprisingly, there has yet to be a cave-in.

Glacial Cave - Unlike the rest of the Surface, the polar ice caps are not radioactive, and are safe to battle in, so sometimes, just that will happen.

Crystal Cavern - The cave where the Light and Dark were found. Sometimes, it is used instead of the Battlegrounds to host a fight.

The Castle - Lost to time, The Castle is where The King resided. The Castle no longer remains due to the war, however, The King can still be spotted in the Battlegrounds.

The War
The war between RED and BLUE was not a simple fight between good and evil. One day, the ruler of the BLUE, The King, discovered a power source called The Dark. The Dark gave The King the power to shape the world around him. However, he could not keep this power a secret for long. The RED leader discovered a similar power, called The Light. The RED leader, only known as cs641311, quickly mastered The Light, and it told him of The King's secret. The next day, they met, and in a blinding flash of the greatest battle ever, a shockwave was released, destroying much of The Surface. All who survived went into the underground tunnels to survive the fallout above.

Present Day
Nowadays, cs641311 and The King can still be seen fighting on the Battlegrounds, along with some other remaining members of RED and BLUE, although, they are not usually joined into a team.

|

To see The King's current form, input the following into the "Load Texturepack" button.

https://lostking73.github.io/Pixel-Tanks/public/js/config.js

|

|

|

Lore Drops
The King that is seen on the battlefield is not his true body. He is hidden away until the time for his rise comes.

New Location has been discovered! Dimensional Barrier: Located deep into the void, it appears to be a maze that separates our dimension from others. Only one being has been known to find the end. The King.

The battle between cs641311 and The King was not a fair fight. cs641311's "kingdom" was simply an outcast camp, whereas The King's castles and power reached further than cs641311 could ever know.

New Location has been discovered! The Deep: "Deep", on the bottom of the ocean, there exists the remains of a long lost battleground. Missions to obtain rare minerals are staged here, however, there is something that lives. . . deep, deep down. The Leviathan.

**Comment by 3foe** [comment]
thats literally whats there

**Comment by BreadSpammer** [comment]
so basically imma move the coins text, then make it so when u hover over a icon, text will appear with the stats and description and stuff :_______:

**Comment by LostKing73** [comment]
> thats literally whats there

it is not.

**Comment by 3foe** [comment]
1 um no its there...
2 I would love to make PERMANENT peace with you, I don't want to have to deal with you forever. what are your terms?

**Comment by 3foe** [comment]
unacceptable, I stay where I am. however you don't have to sty where you are. i want peace but I don't need it. remember I am in charge here. I wish there was another way to have peace even if it is manufactured

**Comment by LostKing73** [comment]
> unacceptable, I stay where I am. however you don't have to sty where you are. i want peace but I don't need it. remember I am in charge here. I wish there was another way to have peace even if it is manufactured

you do not in fact want peace. you want power. you are literally the living embodiment of dum

**Comment by BreadSpammer** [comment]
bruh this is about fixing menus not ur lore/flat arguments. flat will die with time, and we're not adding leviathan unless entire game gets finished and everyone wants it (which they don't)

**Comment by DarkMemeGod411** [comment]
> bruh this is about fixing menus not ur lore/flat arguments. flat will die with time, and we're not adding leviathan unless entire game gets finished and everyone wants it (which they don't)

Amen.

**Comment by 3foe** [comment]
> > unacceptable, I stay where I am. however you don't have to sty where you are. i want peace but I don't need it. remember I am in charge here. I wish there was another way to have peace even if it is manufactured
> 
> you do not in fact want peace. you want power. you are literally the living embodiment of **dum**

that's in violation of your probation

**Comment by 3foe** [comment]
tsk tsk tsk

**Comment by cs6413110** [comment]
Flat, you're on probation too. The ruling being your own definition of admin abuse.

**Comment by CelestialKnight7** [comment]
proposal for the shop descriptions:
(yes this is keengdomez jumpscare)
![lantern_shop_description](https://github.com/user-attachments/assets/5853d0e2-cae5-4736-8804-a531d9664473)

**Comment by cs6413110** [comment]
yes

**Comment by LostKing73** [comment]
> > > unacceptable, I stay where I am. however you don't have to sty where you are. i want peace but I don't need it. remember I am in charge here. I wish there was another way to have peace even if it is manufactured
> > 
> > 
> > you do not in fact want peace. you want power. you are literally the living embodiment of **dum**
> 
> that's in violation of your probation

waaaaa waaaaaaaaa. all I hear is someone who does not matter yapping.

**Comment by LostKing73** [comment]
anyways, more on topic, i divert my work to @CelestialKnight7 cuz lag bye

**Comment by CelestialKnight7** [comment]
I undivert his work to me unlag get back here

**Comment by LostKing73** [comment]
nooooooooooooooooooo

**Comment by LostKing73** [comment]
but im tryna perk spammmmmmmmmmmmmm

**Comment by 3foe** [comment]
no spamming jonas. Github is for productivity not highly personalized attacks

**Comment by BreadSpammer** [comment]
#notmyissue

**Comment by LostKing73** [comment]
so, like this? 
![image](https://github.com/user-attachments/assets/ef1fc35f-2ed2-4e8e-8df0-2d25b56fb901)
like that was too easy to be right...

**Comment by CelestialKnight7** [comment]
why are there save buttons

**Comment by LostKing73** [comment]
> why are there save buttons

idk aaron said to add

**Comment by LostKing73** [comment]
uhm @CelestialKnight7 go to zones
