### ISSUE TITLE
NEW MENUS 2.0 

### ISSUE THREAD

**Issue by 3foenation** [cs6413110/Pixel-Tanks#180]
jonas you opionion is invalid because you always say no
![pixilart-drawing (2)](https://github.com/user-attachments/assets/77be2c1e-76b8-4ef6-bb88-ad2cc6630793)

**Comment by 3foenation** [comment]
tell me what i wrong with it

**Comment by BreadSpammer** [comment]
boring background. literally just /fill instead of a metal grate of the normal one
made the tank look worse than it normally does
text is lazy and not fancy
key binds button died, and help menu is there even though it doesn't exist
circle buttons are cringe because it would be inaccurate (click the corner to go in without actually clicking the button
singleplayer name is offcenter
menu is off theme for the rest of the menus
0 effort

**Comment by BreadSpammer** [comment]
there goes 5 minutes of my time. close

**Comment by LostKing73** [comment]
THANK YOU. DUM.

**Comment by LostKing73** [comment]
"your opinion is invalid because your opinion isn't the same is mine" isn't... like bro that upsets me so much I cant form words to describe it
