### ISSUE TITLE
item issue cuz phase is a scam

### ISSUE THREAD

**Issue by CelestialKnight0** [cs6413110/Pixel-Tanks#275]
stealth has been robbed also some of these are items from the old item issue i made

**Comment by CelestialKnight0** [comment]
oil, flammable/explodable surface that does big damage but requires ignition, eventually will dissipate (after 1 min) but while it is there it can be ignited which will do 300 damage do anyone in the explosion radius.

**Comment by CelestialKnight0** [comment]
mines (apparently ded ig) place 4 mines around u that each do 50 damage

**Comment by CelestialKnight0** [comment]
thermite

 throw a projectile that will stick to something and spew fire around (not actual fire but damage) for 5 seconds.

**Comment by BreadSpammer** [comment]
so all damage items are auto downvote by Aaron because of insta, even though it doesn't insta, and all healing items are auto downvote by Aaron because of flatting. blocks would also be auto downvote. this basically makes all ideas that get added have to be support/dodge items, because otherwise, it gets veto'd. that's why phase shift was added

**Comment by CelestialKnight0** [comment]
not supportive just more unique like reflect or airstrike type items

**Comment by BreadSpammer** [comment]
I havenade unique items, they died.

**Comment by cs6413110** [comment]
Dead due to lack of ideas
