### ISSUE TITLE
Animated cosmetics V2: Kill Response (now flat debate ew)

### ISSUE THREAD

**Issue by LostKing73** [cs6413110/Pixel-Tanks#65]
### The Basics

uhm so like when get kill, cosmetic will become animated for a little bit.

### Why add this?

bcuz duh and like y not

### Voting

👍 = yes
👎 = no (comment why)

**Comment by BreadSpam** [comment]
is in a gud game so sure. maybe make it mythic exclusive. basically so instead of the cringe animations rn, it will play it after kill, for spinage

**Comment by DarkMemeGod411** [comment]
Yeah good idea lk. glad I went on GitHub over break

**Comment by DarkMemeGod411** [comment]
The app's hands look weird

**Comment by CelestialKnight7** [comment]
> is in a gud game so sure. maybe make it mythic exclusive. basically so instead of the cringe animations rn, it will play it after kill, for spinage

**what game**

**Comment by LostKing73** [comment]
why can you change titles.

**Comment by DarkMemeGod411** [comment]
wdym?

**Comment by CelestialKnight7** [comment]
and how would this animate the cosmetic, that means its a flat image the rest of the time and then when you get a kill it does a quick gif that no one cares about or notices. its better and easier to just have it be animated all the time or none of the time rather than have dependent events like this

**Comment by 3foe** [comment]
Everything Evan said, plus lag.

**Comment by LostKing73** [comment]
> wdym?

you changed the title. how can you do that. @cs6413110 remove code access pls

**Comment by 3foe** [comment]
1 dude, you don't need to attack another person, just because they have comparable power to you...

2 you started a war with me and now you are beating a dead horse by attacking Alex, again... 

3 this can be a debate issue or stay on topic you choose.

**Comment by cs6413110** [comment]
For the record, flat chose to start provoking people with his previous post. Solely and exclusively his fault for what results.

**Comment by LostKing73** [comment]
![image](https://github.com/user-attachments/assets/79ee6e38-db17-4eb4-8d7e-e1a50e63fa17)

**Comment by CelestialKnight7** [comment]
ye looks the same. all that changed was the fixed spelling of aniamted

**Comment by 3foe** [comment]
lol, little bro deleted my comment but he's calling me Hitler jr because I deleted his comments. hypocrite moment.

this just validates and reinforces what I said

**Comment by LostKing73** [comment]
> and how would this animate the cosmetic, that means its a flat image the rest of the time and then when you get a kill it does a quick gif that no one cares about or notices. its better and easier to just have it be animated all the time or none of the time rather than have dependent events like this

it would give a reason why like 4 are animated

**Comment by LostKing73** [comment]
> lol, little bro deleted my comment but he's calling me Hitler jr because I deleted his comments. hypocrite moment.
> 
> this just validates and reinforces what I said

"little bro"? what are you, my uncle?

**Comment by 3foe** [comment]
jonas is upset that Alex has code access and because he could change the title it proves he has code access. He wants alex to be declawed and powerless to defend himself before he starts beating down on alex again.

**Comment by 3foe** [comment]
> > lol, little bro deleted my comment but he's calling me Hitler jr because I deleted his comments. hypocrite moment.
> > this just validates and reinforces what I said
> 
> "little bro"? what are you, my uncle?

 that is a weights reference exploitation here: ya know I'm in weights normally little bro is the weakest person in the weights group in this case, you are the weaker person because I am stronger than you in more ways than one.

 on top of that I have 10x (I did the math this is not an exaggeration) times more experience and time in this group I am the original person here I even out-date Aaron when it comes to commitments to tanks because I came up with it, although he did do most of the work.

**Comment by LostKing73** [comment]
flat: 
![image](https://github.com/user-attachments/assets/2ea7ed7d-e8b7-4e8b-a865-f2f256cb845e)

**Comment by 3foe** [comment]
bro just pulled a Hilter Jr. again...

**Comment by cs6413110** [comment]
The only thing you're validating is how much of a flat you are and that every problem you have with anyone on tanks is just a direct result of your own actions.

**Comment by LostKing73** [comment]
napolean complex moment. he thinks thats hitler haha

**Comment by cs6413110** [comment]
You're not even behaving like a real person. You're stuck in the 4 year old roblox mindset of just echoing back whatever you get called.

**Comment by LostKing73** [comment]
> lol, little bro deleted my comment but he's calling me Hitler jr because I deleted his comments. hypocrite moment.
> 
> this just validates and reinforces what I said

difference between clearing hate and  clearing people who speak against you. yk who cleared people who spoke against him? Hitler.

**Comment by 3foe** [comment]
> napolean complex moment. he thinks thats hitler haha

you hide my comments I know that's not Hitler but you pulled a hitler whats next ur going to be a bradley and put Swastikas on maps 

also ur shorter than me do you even know what a Napolean complex even is???????

**Comment by 3foe** [comment]
> napolean complex moment. he thinks thats hitler haha

I know someone else who deletes differing opinions you, hence the last 30 minutes of you hiding or deleting my comments

**Comment by 3foe** [comment]
> > You're not even behaving like a real person. You're stuck in the 4 year old roblox mindset of just echoing back whatever you get called.


I used a label that fits. just because its the one he used on me it doesn't mean its wrong plus bro just called me what he is

**Comment by 3foe** [comment]
> > You're not even behaving like a real person. You're stuck in the 4 year old roblox mindset of just echoing back whatever you get called.
> 
> literally. bro cannot exist past blox fruits

4 yr olds and games have nothing to do with the validity of my points so why bring it up? is this an ad hominine moment A logical fallacy?

**Comment by DarkMemeGod411** [comment]
for the record all I did was change the typo title. I apologize If what I did was wrong

**Comment by cs6413110** [comment]
Flat you literally contribute less, are involved less, and are harmful 100x more than everyone here because of how immature you are. Your own roblox slang of "little bro" applies more to you. Stop lying to yourself that you've contributed anything but obstacles to tanks. For the first few year of development you tried to make fun of it and discourage me. And you didn't start saying people stole your ideas until many months after said ideas were implemented. Tanks should be seperate from you for many reasons. You just can't handle interacting with people because you shoot people down, try to rank those in a friend group in an attempt to elevate yourself, and act like a narcissist.

**Comment by 3foe** [comment]
also I will not belectured about roblox by the guy who stole his moms credit card and spent 900 dollars on roblux

**Comment by LostKing73** [comment]
> > napolean complex moment. he thinks thats hitler haha
> 
> you hide my comments I know that's not Hitler but you pulled a hitler whats next ur going to be a bradley and put Swastikas on maps
> 
> also ur shorter than me do you even know what a Napolean complex even is???????

phew, gotta make a list ig. me hiding ur comments to try to stay on topic isn't an example of me being comparable to hitler. also, a napolean complex has nothing to do with height. "The Napoleon complex, also known as Napoleon syndrome, is a purported condition normally attributed to people with overly aggressive or domineering social behavior. It implies that such behavior is to compensate for the subject's physical or social shortcomings."

**Comment by LostKing73** [comment]
> > > You're not even behaving like a real person. You're stuck in the 4 year old roblox mindset of just echoing back whatever you get called.
> > 
> > 
> > literally. bro cannot exist past blox fruits
> 
> 4 yr olds and games have nothing to do with the validity of my points so why bring it up? is this an ad hominine moment A logical fallacy?

its a your points are not valid.

**Comment by LostKing73** [comment]
> also I will not belectured about roblox by the guy who stole his moms credit card and spent 900 dollars on roblux

lol I did that too. when I was 6

**Comment by cs6413110** [comment]
I haven't even touched roblox in my life. No account, nothing. You're so desperate to try to make yourself look better than everyone that you're resorting to blatant lies. The only person you're tricking is yourself.

Also, $900 of robucks?!?! Not even you are that insane.

**Comment by 3foe** [comment]
> > also I will not belectured about roblox by the guy who stole his moms credit card and spent 900 dollars on roblux
> 
> lol I did that too. when I was 6

you still act 6

**Comment by 3foe** [comment]
your last point was literally brain rot I quote "NUH UHHHH"

**Comment by 3foe** [comment]
the only thing he could do was say your points are not valid but couldn't put up any actual points

**Comment by 3foe** [comment]
do you want to go back the the actual purpose of this or do you still want to debate me

**Comment by LostKing73** [comment]
> the only thing he could do was say your points are not valid but couldn't put up any actual points

me, lists points. flat, erm your rong, roblox roblox

**Comment by CelestialKnight7** [comment]
> > > lol, little bro deleted my comment but he's calling me Hitler jr because I deleted his comments. hypocrite moment.
> > > this just validates and reinforces what I said
> > 
> > 
> > "little bro"? what are you, my uncle?
> 
> that is a weights reference exploitation here: ya know I'm in weights normally little bro is the weakest person in the weights group in this case, you are the weaker person because I am stronger than you in more ways than one.
> 
> on top of that I have 10x (I did the math this is not an exaggeration) times more experience and time in this group I am the original person here I even out-date Aaron when it comes to commitments to tanks because I came up with it, although he did do most of the work.

💀 lol

**Comment by 3foe** [comment]
if he were doing that you would have a point but he's not. like a child he is determining what reality is and is blind the the harsh fact that he is wrong and should try to argue with me and everyone else when he needs everyone to support him. he is censoring different opinions just because they are different and come from me that is targeted censoring. something only a narcasist or some one with a Napolean complex would do note that's exactly what he called me he is just a hipocrite

**Comment by LostKing73** [comment]
☝️ 🤓

**Comment by LostKing73** [comment]
> if he were doing that you would have a point but he's not. like a child he is determining what reality is and is blind the the harsh fact that he is wrong and should try to argue with me and everyone else when he needs everyone to support him. he is censoring different opinions just because they are different and come from me that is targeted censoring. something only a narcasist or some one with a Napolean complex would do note that's exactly what he called me he is just a hipocrite

bro. this is funny tank game. not a socio-economic debate. stop taking the game so seriously, and everything so personal. as evan has said, 

LEAB LONE

**Comment by CelestialKnight7** [comment]
> Flat you literally contribute less,**(literally how)** are involved less **(only because people cant handle dealing with me because you try to slander me with every comment)**, and are harmful 100x more than everyone here because of how immature you are **(slandering is immature)**. Your own roblox **(not roblox slang plus read earlier comment)** slang of "little bro" applies more to you.**(in the actual context it applys to everyone but me)** Stop lying to yourself that you've contributed anything but obstacles to tanks**(the only obstacle is contention which is soly cause by people who cant deal with me because of you slander)**. For the first few year of development you tried to make fun of it and discourage me.**(literally didn't I was your only supporter)** And you didn't start saying people stole your ideas until many months after said ideas were implemented. **(there are no said ideas and the only implemented ideas were my ideas)**Tanks should be seperate from you for many reasons.**( not really I should be the sole voice of reason for many reasons but others are entitled to their opinions)** You just can't handle interacting with people because you shoot people down,**(that's jonas not me)** try to rank those in a friend group in an attempt to elevate yourself, and act like a narcissist. **(when did I rank someone)**

what does bro mean "literally how" you literally halted development entirely with ur little stunt with aaron and have never contributed a good idea

bro i can't even keep reading screw whatever essay i was about to write

**Comment by LostKing73** [comment]
> > > the only thing he could do was say your points are not valid but couldn't put up any actual points
> > 
> > 
> > me, lists points. flat, erm your rong, roblox roblox
> 
> um dude that's you. u brought up Roblox... you only said "Your points are not valid" and now you resort to fallacies as seen in you last comment ad hominine
> 
> and an argument built on a fallacy is a wrong one

thank you for acknowledging your argument is wrong

**Comment by 3foe** [comment]
you brought it up not me, when you lose you don't want to talk anymore. what does that remind me of? a 6 year old

**Comment by CelestialKnight7** [comment]
no one wants you here so if youre so upset with us just leave

**Comment by LostKing73** [comment]
"dont want to talk"? look, you've even woken evan with you hateage

**Comment by 3foe** [comment]
> > > > the only thing he could do was say your points are not valid but couldn't put up any actual points
> > > 
> > > 
> > > me, lists points. flat, erm your rong, roblox roblox
> > 
> > 
> > um dude that's you. u brought up Roblox... you only said "Your points are not valid" and now you resort to fallacies as seen in you last comment ad hominine
> > and an argument built on a fallacy is a wrong one
> 
> thank you for acknowledging your argument is wrong

then prove its built on a fallacy go you have till the end of the day to find a fallacy that my **entire** argument is build on

**Comment by CelestialKnight7** [comment]
narcicsim (great spelling ik)

**Comment by 3foe** [comment]
un no I gave him a chance to win this. also a chance to stop getting comboed for a day all he has to do is find a fallacy and he can win I already found like 3 that he used which makes me the default winner of the debate. his arguments hold no weight because they hold no logic

**Comment by CelestialKnight7** [comment]
nah id close

**Comment by LostKing73** [comment]
just off the top of my head without any study
![image](https://github.com/user-attachments/assets/ab491a4c-1a61-4c5d-853e-67c2de1dcfea)

**Comment by LostKing73** [comment]
> and how would this animate the cosmetic, that means its a flat image the rest of the time and then when you get a kill it does a quick gif that no one cares about or notices. its better and easier to just have it be animated all the time or none of the time rather than have dependent events like this

eh I agree actually

**Comment by 3foe** [comment]
none are valid

**Comment by 3foe** [comment]
i can prove or not up to you

**Comment by LostKing73** [comment]
bro really said "prove me wrong" and when i proved him wrong he said "nuh uh"

**Comment by 3foe** [comment]
You gotta connect the fallacy to the phrase your point is not complete. You said" u did this" but gave no backing or context. it this were debate club you would have been thrown out at the first fallacy you made. 

How did I appeal to fear? Maybe you were afraid but only because you lost. You appealed to force and authority by bringing in Aaron.

 The slippery slope is what you did you said you were silenced by opinion so you must be Hitler.

I didn't say anything would happen to you? so how did I appeal to the consequences.

Appeal to emotion is pathos but I said nothing about it and pathos is a valid arguing point you validated my argument by saying I used pathos so is that a dub?

**Comment by cs6413110** [comment]
1.) You know Jonas is right. And it's not like you've proven a single claim.

2.) You appeal to fear via blackmail. Fact.

3.) That's not slippery slope, that's emphasis by example to show you are behaving like a narcissistic dictator.

4.) You made a list of threats. Stop trying to pretend to be the victim when you are the aggressor.

5.) You're appealing to victimization and hate speech.

**Comment by LostKing73** [comment]
69th

**Comment by 3foe** [comment]
a real oppondent has appeared. someone who can debate. we all know jonas is out of his depth he has no siblings I'm not here to fight Aaron just jonas.

**Comment by 3foe** [comment]
time to debunk his claims :D

**Comment by 3foe** [comment]
1) the entire reason for this isssue is because I know jonas is not right

2) a month ago isn't relevant to the argument

3) its a slippery slope you go from deleting hate because what I deleted was genuine targeted and deliberate hate to being a mass murderur, serial killer and insane man. just because he once censored something or someone for different reasons.

4) it was made of ways that I can influence the situation the ways I could hurt u was to make sure you entered the agreement

5) I'm not appealing to anyone  or anything that is not the goal and I am certainly not appealing to hate speech because I am not appealing to jonas's arguement

**Comment by cs6413110** [comment]
Nah, Jonas just played you. Your little jab that he is "out of his depth he has no siblings" is ad hominem, emotionally charged, and egotistical. We are watching you prove every fallacy and accusation made against you in real time.

**Comment by 3foe** [comment]
He is out of his depth because he has no siblings, therefore he has no practice and cant recognize when he is wrong since it is purely made of logic and since it doesn't suggest that I am better and because it doesn't attack him, it is not egotistical a fallacy or emotionally charged.

**Comment by 3foe** [comment]
also jonas playing me... I dont think he thinks that far. he definitely didn't think that far when he attacked his only 2 freinds

**Comment by cs6413110** [comment]
> 2. a month ago isn't relevant to the argument

Then that nullifies...
- Any accusation of idea stealing
- Claims of original ownership
- Any admin abuse

And what are you left with?

**Comment by 3foe** [comment]
you took that out of contect

**Comment by 3foe** [comment]
something that is questionably blackmail does not change what blackmail is today

**Comment by cs6413110** [comment]
If you use that to diffuse one of my points, then I can state it would take out your entire "argument".

**Comment by 3foe** [comment]
if you can defeat my arguement then you win (for obious reasons) I do not belive you can do so because you would have already debunked and delegitimize my argument instead you have only cause more debate and gotten nowhere.

**Comment by 3foe** [comment]
I debunked that comment already I said it was referring to blackmail a month ago not crimes done a month ago but lets entertain your point for a minute

I am left with:


jonas attacking alex deliberately earlier in the issue

jonas attacking my opinion just because its mine

jonas using invalid points in his argument

**Comment by 3foe** [comment]
also jonases entire attempt at an arguement as seen earlier

**Comment by 3foe** [comment]
plus jonas cyberbullying alex this month

**Comment by 3foe** [comment]
> Your argument de-legitimizes itself. I can't "win" because you are trapped in a static, narcissistic worldview that refuses to acknowledge fact. Don't tell me to repetitively re-prove my singular fact when you can't even justify the existence of your unstable self-revolving world.

so in other words.... ad hominine: This fallacy occurs when, instead of addressing someone's argument or position, you irrelevantly attack the person or some aspect of the person who is making the argument. The fallacious attack can also be direct to membership in a group or institution.

how did he use ad homimine? he flat out said he would not acknowledge my claims and argument simply because it is me saying it so he used my position even though it's not really my position but a false one (further delegitimizing his argument) to ignore my points. I debunked you point and proved it false and by saying you wont re prove it you are saying you wont continue debating me a sign of victory in an argument and at the very least a stalemate. at this point I have won the argument by stale mating aaron and by utterly defeating all of jonas's claims. that's a dub

**Comment by cs6413110** [comment]
Is your sole purpose in life trying to make yourself win in your own eyes? This is exactly what I was saying. I can't "win" because you can't live with the possibility of "losing". Our "arguments", trivial petty nondirectional squabbles, always deviate from their root cause because it's not about an argument, or proving a point. It never was. It was always about proving yourself --- not to others --- but to yourself. You think you have won by "stalemating" me by trapping yourself in a world of lies? Fine. Think that you win. But in reality you have only lost. One day that sense of self-superiority will come crumbling down all at once. Others see it. And one day you will too.

**Comment by 3foe** [comment]
you got one thing right, you cant win. this isnt about proving myself to me this is about showing you you are wrong. one day you will be humble enough to admit it and you will be fixed. I can do my best to accelerate it by proving you wrong whenever I get the chance. when you can stomach being wrong you will be a good person that goes for you and jonas. I will wait for that day

**Comment by LostKing73** [comment]
> plus jonas cyberbullying alex this month

haven't read everything, but not only are YOU cyberbullying, alex has admitted miself that he doesn't deserve admin.

**Comment by LostKing73** [comment]
![image](https://github.com/user-attachments/assets/36c83a77-3935-4bee-af52-3b09250803a3)

**Comment by LostKing73** [comment]
aaron fix by cutting him off. block from the github, remove code, remove full auth. literally. why does he remain. @BreadSpam, @CelestialKnight7

**Comment by LostKing73** [comment]
i honestly cant beleive you are talking down to me like I am a 7 year old mathew. that is truly immature and disrespectful, and the only reason I have not already reported you to the school is because I do not want the github taken down. you need to get your act straight.

**Comment by LostKing73** [comment]
i do not want to get into the whole alex situation, but he bullied, manipulated, and made fun of me. not to mention telling me to kill myself, which he still jokes about.

**Comment by CelestialKnight7** [comment]
ez

**Comment by CelestialKnight7** [comment]
![image](https://github.com/user-attachments/assets/fcd07969-86ae-4f1b-94da-25c2ffca5a3e)
me reading this:

**Comment by LostKing73** [comment]
> For the record, flat chose to start provoking people with his previous post. Solely and exclusively his fault for what results.

bro predicted him

**Comment by LostKing73** [comment]
> For the record, flat chose to start provoking people with his previous post. Solely and exclusively his fault for what results.

bro predicted him

**Comment by DarkMemeGod411** [comment]
ye

**Comment by DarkMemeGod411** [comment]
I don't want to get involved in this argument. it will destroy tanks, (again btw). 3foe stop the wars.

**Comment by DarkMemeGod411** [comment]
> i honestly cant beleive you are talking down to me like I am a 7 year old mathew. that is truly immature and disrespectful, and the only reason I have not already reported you to the school is because I do not want the github taken down. you need to get your act straight.

truce. He is talking down and trying to destroy you with arguments. The disrespect shown to you is disgusting.

**Comment by 3foe** [comment]
you see here is the thing. if you are saying its you or me who leaves, you leave because I cannot so bye. so stop making issue and we wont have to boot you

**Comment by DarkMemeGod411** [comment]
boot who?

**Comment by LostKing73** [comment]
literally. cs. cut flat off. remove him.

**Comment by 3foe** [comment]
he attacked me and I systematically discredited his arguments his faults

**Comment by 3foe** [comment]
jonas duh

**Comment by 3foe** [comment]
I dont think u get it jonas he cant. he just can't however he can boot you off and if you keep causing wars we will boot you

**Comment by DarkMemeGod411** [comment]
Stop the fight, Its not worth losing the GitHub. Stop the arguments. and what did I do?

**Comment by LostKing73** [comment]
> he attacked me and I systematically discredited his arguments his faults

no plan, just yappage
![image](https://github.com/user-attachments/assets/36ca28b7-2eda-48f4-8f23-7ddb9212c8e7)

**Comment by 3foe** [comment]
if you keep acting like a 7 year old or a 6 year old I will keep talking too you as such. I will not give you more respect than you deserve.

**Comment by DarkMemeGod411** [comment]
STOP!

**Comment by LostKing73** [comment]
> I dont think u get it jonas he cant. he just can't however he can boot you off and if you keep causing wars we will boot you

YOU are causing wars. THIS IS ALL YOUR FAULT AND YOUR FAULT ALONE.

**Comment by 3foe** [comment]
all in favor of booting jonas? vote here

**Comment by DarkMemeGod411** [comment]
No. Mattew. Do you understand me. All this is gonna cause is the death of tanks. No one gets booted.

**Comment by DarkMemeGod411** [comment]
> > plus jonas cyberbullying alex this month
> 
> haven't read everything, but not only are YOU cyberbullying, alex has admitted miself that he doesn't deserve admin.

he hasn't said my name until now, so wrong, and mattew is cyber bullying

**Comment by 3foe** [comment]
![image](https://github.com/user-attachments/assets/c52d9a06-aedc-4a46-80da-2626c0f524c9)

**Comment by 3foe** [comment]
not cyber bullying. like how, he started beefing with me when I told him to chill.

**Comment by 3foe** [comment]
he deleted my comments 3 times before I got on his case tried to remove your code access 3 times as well and then tried to override my opinion and Evans's opinion

**Comment by 3foe** [comment]
his fault his arguement, he wanted this and he got what he deserved

**Comment by cs6413110** [comment]
This is about you, not Jonas.

**Comment by cs6413110** [comment]
Literally whenever you get called out you bring it back to blaming others.

**Comment by 3foe** [comment]
... I made my point if you insist on being blind to it it just proves my point further. jonas can never regain my respect but he my be able to gain the respect of others he meets if he learns how to deal with people if you shield him from that reality then you are hurting him rather than helping him

**Comment by LostKing73** [comment]
> ... I made my point if you insist on being blind to it it just proves my point further. jonas can never regain my respect but he my be able to gain the respect of others he meets if he learns how to deal with people if you shield him from that reality then you are hurting him rather than helping him

flat. you a are what is being discussed. get my name out of your lying, immature mouth.

**Comment by LostKing73** [comment]
what does "the origin of 5 year olds stealing their moms credit card to buy robux" have to do with this? sounds like an ad homineminem or whatever

**Comment by 3foe** [comment]
gald you know what it is. now that you recognize what an ad hominem is I hope you will stop using it.

I will 'cool off' when you have apologized to Alex personally for cyberbullying him. and don't say he got what he deserved because he didn't. that's all I have to say I'm not going to debate you like this again because my goal is not to embarrass you or discredit you or punish you for something, you have every right to be mad at me and vice versa, but you do not have a right to be mad at Alex.

**Comment by LostKing73** [comment]
"but you do not have a right to be mad at Alex." _excuse me?_ are you in your right mind (retorical question)? again. alex has bullied, manipulated, and made fun of me. not to mention telling me to kill myself, which he still jokes about.

**Comment by cs6413110** [comment]
Flat, you've failed at the only two things being an admin gives you: the responsibility to keep the tanks chat safe and constructive, and using commands to make the game more fun and enjoyable for others. You provoke and spark cyber bullying with every press of poor Github's comment button. You abuse admin to make the game less fun for others, the very thing you said you were against for so long. At least other people were funny about using commands, you're just blatantly disrespectful. This is why everyone wants you gone. Not only are you bad at the job you blackmailed others into getting, you are the very thing said job keeps in check.

And just so you can see it...
**Vote if you don't think flat deserves full-auth**
@DarkMemeGod411 @BreadSpam @CelestialKnight7 @LostKing73

**Comment by 3foe** [comment]
this is a biased vote plus it doesn't matter. so don't care back to the discussion jonas you blackmailed Alex first. everything you say Alex did to you you did to him except more sever. not even going to bother debunking your claims they are just wrong because they are factually inaccurate, and you wouldn't even recognize that you lost because you cant be wrong in your own version of reality. don't say I'm just circling because it applies to you perfectly and is not meant to deflect blame, it is simply the truth.

**Comment by LostKing73** [comment]
this is a biased vote

**no crap**

 plus it doesn't matter. 

**neither does your opinion, yet you keep saying it does.**

so don't care back to the discussion jonas you blackmailed Alex first. 

**what "blackmail" did I do? alex offered HIMSELF to 3d print for me, just to eventually make me have him actually tell me he doesn't even HAVE a 3d printer.** 

everything you say Alex did to you you did to him except more sever. 

**i did not bully nor manipulate him, or tell him to kill himself. i had a disdain for him because of how he treated me.**

not even going to bother debunking your claims they are just wrong because they are factually inaccurate,

**you SAY they are, but they are accurate**

 and you wouldn't even recognize that you lost because you cant be wrong in your own version of reality.

that is literally what you are doing. there is no "I lost" because I didn't do anything wrong. you are taking points from something that is not true from someone who admits to being a manipulator, and twisting them to attack me instead of giving reasons why YOU are right, instead of why I am in the wrong.

 don't say I'm just circling because it applies to you perfectly and is not meant to deflect blame, it is simply the truth.

It is not true, and is specifically so you are not in the limelight.

**Comment by LostKing73** [comment]
THAT is systematically debunking your argument. not whatever you were doing

**Comment by DarkMemeGod411** [comment]
I blackmailed first

**Comment by cs6413110** [comment]
Tbh the only thing we lost was our time.

**Comment by CelestialKnight7** [comment]
the real blackmail was the braincells we lost along the way

**Comment by 3foe** [comment]
not responding to whatever jonas just did. like just spewing at this point so not even worth responding to and nothing he said was even remotely true
