### ISSUE TITLE
Fix Death Effects

### ISSUE THREAD

**Issue by BreadSpam** [cs6413110/Pixel-Tanks#8]
plz they were so funny. if readd, then I will make a crystal one

**Comment by cs6413110** [comment]
deferred to 2027

**Comment by BreadSpam** [comment]
k um VOTE @cs6413110 @CelestialKnight7 @LostKing73 @DarkMemeGod411

**Comment by DarkMemeGod411** [comment]
Add

**Comment by cs6413110** [comment]
Voted yes to defer :)

**Comment by DarkMemeGod411** [comment]
they need to be fixed. They were fun. ok here we go.
death effects were fun because they added fun to getting killed. without them, deaths are somewhat boring, the reason for them was to provide a cosmetic for death, they add customization

**Comment by CelestialKnight7** [comment]
bro _thats_ your essay. AH HEM

Death effects should be re-added because they added another layer of customization to the game while also being humorous. While we can't add executions to tanks, death effects stand in and act as another way to show you got a kill and to show who got it as most of the time people have different death effects allowing you to easily tell who just got healing items and is about to insta you. On the customization note, it was another way to personalize your experience which as a gamer myself I really enjoy. Just ask breadly when we played terraria, I would spend too much time crafting or searching for dyes so I could have the peak drip. Customization in video games is something crucial to the experience as it allows you to personalize your experience and also make yourself just look cooler, which everyone wants. Death effects, while they dont directly make you look better (or worse if you want), they do allow you to express yourself. Pick a serious one like nuke, pick a silly one like the skull emoji which exists for some reason, or pick one in between like the right-click delete one. Whichever one you pick it will allow you to customize the game to fix you and your wants and your personality. 
Furthermore if we keep death effects removed that means I have to edit the inventory menu again to remove the slot for them which is pain, Furthermore death effects were somehow where people like bradley and jonas put most of their quality effort (more than normal cosmets atleast). Theres some funny and actually good looking stuff in the github folder for it right now and it would be a shame to see that quality effort go to waste.
On a better note, if death effects were re-added you could tell bradley and jonas to stop spamming and go make death effects because clearly bradley doesnt make cosmets anymore and the only cosmets jonas makes are crown remakes. Swiftly moving on from that though as to not cause another argumnet on cosmets, death effects add so much to the game and have actual quality behind them aswell as the fact that they also give an in game gameplay mechanic of knowing who got the kill without looking at chat (which doesn't update). In conclusion, add death effects.

**Comment by DarkMemeGod411** [comment]
Ok, nice essay.
I can agree about video game customization. (too much so)

**Comment by BreadSpam** [comment]
ok wat "breadly" like u spelleditwrong

**Comment by CelestialKnight7** [comment]
breadly = braldey = bread = "FIXXXXXX"

**Comment by BreadSpam** [comment]
wat

**Comment by BreadSpam** [comment]
its breadley btw

**Comment by LostKing73** [comment]
no? breadly

**Comment by LostKing73** [comment]
breadley sounds like breh-deli, breadly is bread-lee

**Comment by DarkMemeGod411** [comment]
@LostKing73

**Comment by BreadSpam** [comment]
save. btw @cs6413110 FIXXXXXXXX

**Comment by DarkMemeGod411** [comment]
the adventure time deer. WAIT.

**Comment by DarkMemeGod411** [comment]
its funny and took a lot of work

**Comment by LostKing73** [comment]
no. thats low effort, theivery, and just not that good of a reference. it also makes no sense for this game.

**Comment by DarkMemeGod411** [comment]
btw does anyone have a working 3d printer to print A working axe bass.?

**Comment by BreadSpam** [comment]
Ok and?? Doesn't even work as a death effect. Literally just a random gif

**Comment by BreadSpam** [comment]
so like no

**Comment by cs6413110** [comment]
done

**Comment by BreadSpam** [comment]
:DDDDDDDDDDDDDDdd the like button purchase in action

**Comment by BreadSpam** [comment]
^^^^^^
![pixil-frame-0 - 2024-09-26T105457 369](https://github.com/user-attachments/assets/789f1592-a645-4b69-bd32-239c23f9a73e)
